#!/usr/bin/env zsh

set -euC

#Terminate already runninginstances
killall -q dunst

USER_ID=$(whoami)

# Wait until the processes have been shut down
while pgrep -u $USER_ID -x dunst > /dev/null; do sleep 1; done

#CONFIG_FILE="$HOME/.config/dunst/dunstrc"
dunst &
